version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - nginx
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/fastapi.conf:/etc/nginx/conf.d/fastapi.conf
